name: cinitiq_chat_sdk
description: A Flutter SDK for integrating Cinitiq AI chat using WebView with built-in authentication, customizable headers, branded UI, and simple one-line implementation.
version: 1.0.1
homepage: https://github.com/ashrfomari93
repository: https://github.com/ashrfomari93/cinitiq_chat_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
