name: cinitiq_chat_sdk
description: A Flutter package to open Cinitiq AI chat inside a WebView.
version: 1.0.0
homepage: https://github.com/ashrfomari93/cinitiq_chat_sdk
repository: https://github.com/ashrfomari93/cinitiq_chat_sdk
publish_to: 'https://pub.dev'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
